### ISSUE TITLE
Buster issue on tasks Fix libssl error RAC1170

### ISSUE THREAD

**Issue by roumano** [ipr-cnrs/openmanage#2]
The tasks is failling : 
```
TASK [ipr-cnrs.openmanage : Fix libssl error RAC1170] ****************************************************************************************************************************
fatal: [epnkvmext3]: FAILED! => {"changed": false, "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2", "path": "/opt/dell/srvadmin/lib64/libssl.so", "src": "/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2"}
```

As the source `/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2` is not exist (at least) in buster
but the `/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0` exist

The role should find the lastest ssl lib 1.0.x version and use it instead of 1.0.2 hardcoded version

**Comment by gardouille** [comment]
Hi @roumano and thanks for the report.

Yeah it was a good idea at the moment cause it solved the issue but not on the long term :D 

Did you manually try libssl.so.1.0.0 and had Openmanage working on a Debian Buster?
Did you kept 910|911 version or tried a recent one that's only support ubuntu?

Cause Dell doesn't officially support it… http://linux.dell.com/repo/community/openmanage/

**Comment by gardouille** [comment]
Humm `libssl1.0.x` doesn't seem available anymore on Debian Buster…
[List of libssl related packages on Debian Buster](https://packages.debian.org/search?keywords=libssl&searchon=names&suite=stable&section=all). Maybe you have some legacies from Stretch -> Buster migration? ^^

Only `libssl1.1` is available. I hope it will still fix the issue…

Instead of searching for the last `/usr/lib/x86_64-linux-gnu/libssl.so.1.*` version, i can try to add *libssl-dev* package cause it already do the job (create a symlink `/usr/lib/x86_64-linux-gnu/libssl.so` to the last available version).
Any opinions on this?
